services:  
  gesdinet.jwtrefreshtoken.refresh_token_manager:
    class: Praetorian\RefreshTokenManagerBundle\Doctrine\RefreshTokenManager
    public: true
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - 'Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken'